- name: Create group
  ansible.builtin.group:
    name: "{{ group_name }}"
    state: present

- name: Create user
  ansible.builtin.user:
    name: "{{ user_name }}"
    group: "{{ group_name }}"
    state: present
